/**
 * 
 */
package ch.epfl.sweng.androfoot.network;

/**
 * @author Sidney Barthe
 * Will have the ability to convert messages generated by the local game, convert
 * them to strings and send them through a connection.
 */
public class MessageSender {
	// TODO
}
